Skip revoking tokens
dimagi/commcare-analytics pull request #56
Opened 2024-08-22 10:00 UTC by mkangia

https://dimagi.atlassian.net/browse/SC-3819?focusedCommentId=343383

In case of concurrent requests by repeaters one new token revokes the other one which leads into a cycle of revocations.

2024-08-22 10:05 UTC, mkangia commented
Hey @kaapstorm 

Requesting for a review on this.

I would like to deploy this on staging only for now and see how it goes.

2024-08-22 10:38 UTC, kaapstorm approved these changes
Approving for the sake of experimenting. But I worry that this is answering the wrong question.

If we don't revoke expired tokens, then tokens effectively never expire because they would be valid forever.

So (for now) why don't we rather just issue tokens that expire in, say, 12 months? Or a random period between 6 and 12 months? That would have the same outcome -- (after the initial refresh) they don't get revoked.

What Google does is set a short expiry for the first token, and set a long (like 6 months) expiry for refresh tokens. Maybe (at some point in the future, not now) we could do something like that, where the first token is only used for the initial import, and the refresh token is used for syncing? I'm not sure. But I think if we set expiry to 12 months it gives us some time to think about it.

2024-08-22 13:14 UTC, mkangia commented
Noted @kaapstorm 

I hear you. I will definitely add some value for `expires_in` before releasing this to production.
Currently not expiring at all from CCA end to keep it straightforward.

As of now, will just deploy to staging to test. And then will also test with expiry.

2024-08-22 19:06 UTC, mkangia commented
Hey @kaapstorm 

I changed my approach. Since each request from repeater, takes a new token, the expiry time is redundant so I set it to the smallest possible value which should not cause any trouble.

Description is updated as well.

I tested this on staging and everything went well.

This should be good to deploy to production now.
The follow up can be taken at its own time and is not a blocker for this.

2024-08-22 21:38 UTC, kaapstorm commented
> Since each request from repeater, takes a new token

Really?! HQ is supposed to save the last token in `ConnectionSettings.last_token_aes`. Maybe it's not saving it. Or maybe it's not using the token it saved. :thinking:  :unamused: 

What happens if we set `expires_in=365 * 24 * 60 * 60` ?

2024-08-23 08:31 UTC, kaapstorm commented
I wonder if this is related: https://dimagi.sentry.io/issues/5746233109/?project=136860

2024-08-23 08:38 UTC, kaapstorm requested changes
On further consideration, I don't think this is a good idea. I think we should rather fix the way that tokens are managed in CommCare than break the way that tokens are managed in CCA, even temporarily.

If fixing the way that tokens are managed in CommCare turns out to be difficult, we can revisit this approach.

2024-08-23 10:08 UTC, mkangia commented
> Really?! HQ is supposed to save the last token in ConnectionSettings.last_token_aes. Maybe it's not saving it. Or maybe it's not using the token it saved

It seems to be and I believe that has been the core of misunderstanding here.  Do you know where I can look to confirm?


> What happens if we set expires_in=365 * 24 * 60 * 60 ?

As for how things are now, the token won't ever be used again and will stay active for one year.
Even when, expires_in was 0, new tokens were being requested.

2024-08-23 21:27 UTC, mkangia commented
Hey @kaapstorm 

> than break the way that tokens are managed in CCA

Just to be clear about what changes here.

As of now any old tokens for the client stay in DB and are marked as revoked.

After this change, the tokens wont be marked as revoked and will expire after 10 seconds.

I don't think that change is making it worse. Let me know if you think otherwise.

Additionally, to support the change here,
And irrespective of the motivation here, it does seem its better to expire tokens rather than manually revoking them unless its a requirement of OAuth that at once, only one token should be valid for a client.

2024-08-26 08:48 UTC, kaapstorm approved these changes

2024-08-27 09:17 UTC, merged

2024-08-27 09:17 UTC, mkangia commented
Releasing this on staging first

2024-08-27 09:47 UTC, mkangia commented
Tested on staging, things working fine
1. New login
2. Refresh
3. Repeaters from HQ

Deployed to production as well.

2024-08-27 11:01 UTC, mkangia commented
Hey @kaapstorm 

> I'm not sure what you mean by "manually" here

I was referring to this task that I removed in this [commit](https://github.com/dimagi/commcare-analytics/pull/56/commits/4c73ffd45200a43326a72795e15e7530eb349196#diff-2f0793ff3f61bb533690fde0611fc67279c392df6f0ca70a5a7ba6b8b2c4769dL21)

> Based on that definition, it sounds like CCA doesn't have to revoke an old token when a new token is requested. (In other words, we're good.)

Ah! Very nice. That gives me more confidence in our approach here.